project:
  type: book
  output-dir: _book

book:
  title: "Test-book"
  downloads: [pdf]
  date: last-modified
  date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
  references: references.qmd
  back-to-top-navigation: true
  page-navigation: true

bibliography: references.bib

format:
  html:
    shift-heading-level-by: 1
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    theme:
       light: cosmo
       dark: darkly
    code-tools: true
    code-fold: true
    code-link: true
    fig-cap-location: top
    html-math-method: mathjax
    number-sections: true
    number-depth: 3
    toc-depth: 3
    code-summary: "Show R code"
    css: custom.scss
  pdf:
    toc: true
    fig-pos: "H"
    hyperrefoptions:
    - bookmarksnumbered=true
    toc-title: Contents
    links-as-notes: true
    df-print: tibble
    documentclass: scrbook
    classoption: [twoside=off]
    shift-heading-level-by: 1
    toc-depth: 2
    number-sections: true
    number-depth: 3
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true

execute:
  warning: false
  message: false
  cache: true
  freeze: auto  # re-render only when source changes

editor: source

