project:
  output-dir: _slides
  render:
    - index.qmd
    - intro.qmd
    - summary.qmd

format:
  revealjs:
    theme: dark
    embed-resources: true
    fig-cap-location: top
    html-math-method: mathjax
    smaller: false
    number-sections: true
    number-depth: 3
    slide-number: true
    shift-heading-level-by: -1
    slide-level: 2
    scrollable: true
    echo: true
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    # code-overflow: scroll
    auto-stretch: true
    # out-width: "50%"
    fig-height: 3
    fig-width: 7
    # chalkboard: true

execute:
  warning: false
  message: false
  cache: true
  freeze: auto  # re-render only when source changes
