project:
  output-dir: _slides
  render:
    - intro-to-GLMs.qmd
    - intro-MLEs.qmd
    - glms.qmd
    - Linear-models-overview.qmd
    - logistic-regression.qmd
    - count-regression.qmd
    - time-to-event-models.qmd
    - intro-to-survival-analysis.qmd
    - proportional-hazards-models.qmd
    - coxph-model-building.qmd
    - parametric-survival-models.qmd

format:
  revealjs:
    theme: dark
    embed-resources: true
    fig-cap-location: top
    html-math-method: mathjax
    smaller: false
    number-sections: true
    number-depth: 2
    slide-number: true
    slide-level: 2
    scrollable: true
    echo: true
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    # code-overflow: scroll
    auto-stretch: true
    # out-width: "50%"
    fig-height: 3
    fig-width: 7
    # chalkboard: true

execute:
  warning: false
  message: false
  cache: true
  freeze: auto  # re-render only when source changes
